config/routes.rb
Rails.application.routes.draw do
  resources :coordinates
  resources :students
  resources :students
  resources :registers
  resources :polygons
  resources :grades
  resources :schools
  resources :schools

end

app/models/grade.rb
class Grade < ActiveRecord::Base
	belongs_to :school
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
  before_action :set_grade, only: [:show, :edit, :update, :destroy]

  # GET /grades
  # GET /grades.json
  def index
    @grades = Grade.all
  end

  # GET /grades/1
  # GET /grades/1.json
  def show
  end

  # GET /grades/new
  def new
    @grade = Grade.new
  end

  # GET /grades/1/edit
  def edit
  end

  # POST /grades
  # POST /grades.json
  def create
    @grade = Grade.new(grade_params)

    respond_to do |format|
      if @grade.save
        format.html { redirect_to @grade, notice: 'Grade was successfully created.' }
        format.json { render :show, status: :created, location: @grade }
      else
        format.html { render :new }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grades/1
  # PATCH/PUT /grades/1.json
  def update
    respond_to do |format|
      if @grade.update(grade_params)
        format.html { redirect_to @grade, notice: 'Grade was successfully updated.' }
        format.json { render :show, status: :ok, location: @grade }
      else
        format.html { render :edit }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grades/1
  # DELETE /grades/1.json
  def destroy
    @grade.destroy
    respond_to do |format|
      format.html { redirect_to grades_url, notice: 'Grade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grade
      @grade = Grade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grade_params
      params.require(:grade).permit(:space_available, :name)
    end
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/views/grades/_form.html.erb
<%= form_for(@grade) do |f| %>
  <% if @grade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@grade.errors.count, "error") %> prohibited this grade from being saved:</h2>

      <ul>
      <% @grade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :space_available %><br>
    <%= f.number_field :space_available %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/grades/edit.html.erb
<h1>Editing Grade</h1>

<%= render 'form' %>

<%= link_to 'Show', @grade %> |
<%= link_to 'Back', grades_path %>

app/views/grades/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Grades</h1>

<table>
  <thead>
    <tr>
      <th>Space available</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @grades.each do |grade| %>
      <tr>
        <td><%= grade.space_available %></td>
        <td><%= grade.name %></td>
        <td><%= link_to 'Show', grade %></td>
        <td><%= link_to 'Edit', edit_grade_path(grade) %></td>
        <td><%= link_to 'Destroy', grade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Grade', new_grade_path %>

app/views/grades/new.html.erb
<h1>New Grade</h1>

<%= render 'form' %>

<%= link_to 'Back', grades_path %>

app/views/grades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Space available:</strong>
  <%= @grade.space_available %>
</p>

<p>
  <strong>Name:</strong>
  <%= @grade.name %>
</p>

<%= link_to 'Edit', edit_grade_path(@grade) %> |
<%= link_to 'Back', grades_path %>