config/routes.rb
Rails.application.routes.draw do
  resources :coordinates
  resources :students
  resources :students
  resources :registers
  resources :polygons
  resources :grades
  resources :schools
  resources :schools

end

app/models/student.rb
class Student < ActiveRecord::Base
	belongs_to :register
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:latitude, :longitude, :name, :cep, :birth_data, :responsible_name, :responsible_cpf, :intented_grade)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :cep %><br>
    <%= f.text_field :cep %>
  </div>
  <div class="field">
    <%= f.label :birth_data %><br>
    <%= f.date_select :birth_data %>
  </div>
  <div class="field">
    <%= f.label :responsible_name %><br>
    <%= f.text_field :responsible_name %>
  </div>
  <div class="field">
    <%= f.label :responsible_cpf %><br>
    <%= f.text_field :responsible_cpf %>
  </div>
  <div class="field">
    <%= f.label :intented_grade %><br>
    <%= f.text_field :intented_grade %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Students</h1>

<table>
  <thead>
    <tr>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Name</th>
      <th>Cep</th>
      <th>Birth data</th>
      <th>Responsible name</th>
      <th>Responsible cpf</th>
      <th>Intented grade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.latitude %></td>
        <td><%= student.longitude %></td>
        <td><%= student.name %></td>
        <td><%= student.cep %></td>
        <td><%= student.birth_data %></td>
        <td><%= student.responsible_name %></td>
        <td><%= student.responsible_cpf %></td>
        <td><%= student.intented_grade %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Latitude:</strong>
  <%= @student.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @student.longitude %>
</p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Cep:</strong>
  <%= @student.cep %>
</p>

<p>
  <strong>Birth data:</strong>
  <%= @student.birth_data %>
</p>

<p>
  <strong>Responsible name:</strong>
  <%= @student.responsible_name %>
</p>

<p>
  <strong>Responsible cpf:</strong>
  <%= @student.responsible_cpf %>
</p>

<p>
  <strong>Intented grade:</strong>
  <%= @student.intented_grade %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>