config/routes.rb
Rails.application.routes.draw do
  resources :coordinates
  resources :students
  resources :students
  resources :registers
  resources :polygons
  resources :grades
  resources :schools
  resources :schools

end

app/models/polygon.rb
class Polygon < ActiveRecord::Base
	has_many :coordinate
end

app/controllers/polygons_controller.rb
class PolygonsController < ApplicationController
  before_action :set_polygon, only: [:show, :edit, :update, :destroy]

  # GET /polygons
  # GET /polygons.json
  def index
    @polygons = Polygon.all
  end

  # GET /polygons/1
  # GET /polygons/1.json
  def show
  end

  # GET /polygons/new
  def new
    @polygon = Polygon.new
  end

  # GET /polygons/1/edit
  def edit
  end

  # POST /polygons
  # POST /polygons.json
  def create
    @polygon = Polygon.new(polygon_params)

    respond_to do |format|
      if @polygon.save
        format.html { redirect_to @polygon, notice: 'Polygon was successfully created.' }
        format.json { render :show, status: :created, location: @polygon }
      else
        format.html { render :new }
        format.json { render json: @polygon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /polygons/1
  # PATCH/PUT /polygons/1.json
  def update
    respond_to do |format|
      if @polygon.update(polygon_params)
        format.html { redirect_to @polygon, notice: 'Polygon was successfully updated.' }
        format.json { render :show, status: :ok, location: @polygon }
      else
        format.html { render :edit }
        format.json { render json: @polygon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /polygons/1
  # DELETE /polygons/1.json
  def destroy
    @polygon.destroy
    respond_to do |format|
      format.html { redirect_to polygons_url, notice: 'Polygon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_polygon
      @polygon = Polygon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def polygon_params
      params.require(:polygon).permit(:name)
    end
end

app/helpers/polygons_helper.rb
module PolygonsHelper
end

app/views/polygons/_form.html.erb
<%= form_for(@polygon) do |f| %>
  <% if @polygon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@polygon.errors.count, "error") %> prohibited this polygon from being saved:</h2>

      <ul>
      <% @polygon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/polygons/edit.html.erb
<h1>Editing Polygon</h1>

<%= render 'form' %>

<%= link_to 'Show', @polygon %> |
<%= link_to 'Back', polygons_path %>

app/views/polygons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Polygons</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @polygons.each do |polygon| %>
      <tr>
        <td><%= polygon.name %></td>
        <td><%= link_to 'Show', polygon %></td>
        <td><%= link_to 'Edit', edit_polygon_path(polygon) %></td>
        <td><%= link_to 'Destroy', polygon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Polygon', new_polygon_path %>

app/views/polygons/new.html.erb
<h1>New Polygon</h1>

<%= render 'form' %>

<%= link_to 'Back', polygons_path %>

app/views/polygons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @polygon.name %>
</p>

<%= link_to 'Edit', edit_polygon_path(@polygon) %> |
<%= link_to 'Back', polygons_path %>