config/routes.rb
Rails.application.routes.draw do
  resources :coordinates
  resources :students
  resources :students
  resources :registers
  resources :polygons
  resources :grades
  resources :schools
  resources :schools

end

app/models/school.rb
class School < ActiveRecord::Base
	has_many :grade
	belongs_to :polygon
	belongs_to :register
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit, :update, :destroy]

  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url, notice: 'School was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_params
      params.require(:school).permit(:name, :city_name, :room_quantity)
    end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.erb
<%= form_for(@school) do |f| %>
  <% if @school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% @school.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :city_name %><br>
    <%= f.text_field :city_name %>
  </div>
  <div class="field">
    <%= f.label :room_quantity %><br>
    <%= f.number_field :room_quantity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schools/edit.html.erb
<h1>Editing School</h1>

<%= render 'form' %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

app/views/schools/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Schools</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>City name</th>
      <th>Room quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schools.each do |school| %>
      <tr>
        <td><%= school.name %></td>
        <td><%= school.city_name %></td>
        <td><%= school.room_quantity %></td>
        <td><%= link_to 'Show', school %></td>
        <td><%= link_to 'Edit', edit_school_path(school) %></td>
        <td><%= link_to 'Destroy', school, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New School', new_school_path %>

app/views/schools/new.html.erb
<h1>New School</h1>

<%= render 'form' %>

<%= link_to 'Back', schools_path %>

app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @school.name %>
</p>

<p>
  <strong>City name:</strong>
  <%= @school.city_name %>
</p>

<p>
  <strong>Room quantity:</strong>
  <%= @school.room_quantity %>
</p>

<%= link_to 'Edit', edit_school_path(@school) %> |
<%= link_to 'Back', schools_path %>